defaults:
  - base

trainer:
  experiment_name: frozenlake-main

system:
  CUDA_VISIBLE_DEVICES: "4,5,6,7"

es_manager:
  train:
    env_configs:
      tags: ["CoordFrozenLake"]
  val:
    env_configs:
      tags: ["CoordFrozenLake"]
